name: Go Release Builder

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build binary
        run: |
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          go build -o myprogram-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./myprogram-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: myprogram-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_content_type: application/octet-stream